//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class App

{
    private long _balance = 0;
    private long _totalIncome = 0;
    private long _totalOutcome = 0;

    public virtual long balance
    {
        get { return _balance; }
        set { _balance = value; }
    }

	public virtual long totalIncome
	{
        get { return _totalIncome; }
        set { _totalIncome = value; }
	}

	public virtual long totalOutcome
	{
        get { return _totalOutcome; }
        set { _totalOutcome = value; }
	}


	public virtual void countBalance()
	{
        balance = totalIncome - totalOutcome;
	}

	public virtual long countTotalIncome(long income)
	{
        return totalIncome = totalIncome + income;
	}

	public virtual long countTotalOutcome(long outcome)
	{
        return totalOutcome = totalOutcome + outcome;
	}

	public virtual long getBalance()
	{
        return balance;
	}

    public virtual string getAnalysys()
	{
        return "Your total income: " + totalIncome + "and total outcome: " + totalOutcome;
	}

    
    public App()
    {
    }

}

