//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class User
{
    private string _username;
    public App app;
	public virtual string username
	{
        get { return _username; }
        set { _username = value; }
	}


	public virtual string getUsername()
	{
        return username;
	}

    public User(string uname)
    {
        username = uname;
        app = new App();
    }

	public static void Main(string[] args)
	{
        User user1 = new User("msm");

        user1.app.countTotalIncome(10000);
        user1.app.countTotalOutcome(10);
        user1.app.countTotalOutcome(250);

        user1.app.getBalance();
        user1.app.getAnalysys();

	}

}

